################################################################################################
# Replica power sensor, read from source, from target to show on target Home Assistant instance.
# huawei_solar_replicate: v1.0.0
#
# Link: https://github.com/JacobsenKim/ha_huawei_solar_replicate
# How2: https://github.com/JacobsenKim/ha_huawei_solar_replicate/wiki
#
################################################################################################
#
##########################################################################
## !!!!!! Always make sure to back up everything before you begin !!!!! ##
##########################################################################
#
# Replica sensors =
#
# sensor.inverter_input_power (from the Huawei Solar integration)
# sensor.inverter_input_power_2 (from the Huawei Solar integration)
# sensor.inverter_active_power (from the Huawei Solar integration)
# sensor.power_meter_active_power (from the Huawei Solar integration)
# sensor.power_meter_consumption (from the Huawei Solar integration)
# sensor.battery_charge_discharge_power (from the Huawei Solar integration)
# sensor.battery_state_of_capacity (from the Huawei Solar integration)
# sensor.power_meter_exported (from the Huawei Solar integration)
# sensor.battery_day_charge (from the Huawei Solar integration)
# sensor.battery_day_discharge (from the Huawei Solar integration)
# sensor.inverter_daily_yield  (from the Huawei Solar integration)
#
############################################################################
## Replace to fit youre info:  ( ip, Authorization token, scan_interval ) ##
############################################################################
############################################################################
## Replace to fit youre info:  ( ip, Authorization token, scan_interval ) ##
############################################################################
############################################################################
## Replace to fit youre info:  ( ip, Authorization token, scan_interval ) ##
############################################################################
#
sensor:
# sensor.inverter_input_power
  - platform: rest
    name: "Inverter Input Power"
    unique_id: "inverter_input_power"
    resource: "http://192.168.10.24:8123/api/states/sensor.inverter_input_power"
    method: GET
    headers:
      Authorization: "Bearer YOUR_LONG_LIVED_ACCESS_TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 5
    icon: mdi:flash
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: "power"

# sensor.inverter_input_power_2
  - platform: rest
    name: "Inverter Input Power 2"
    unique_id: "inverter_input_power_2"
    resource: "http://192.168.10.24:8123/api/states/sensor.inverter_input_power_2"
    method: GET
    headers:
      Authorization: "Bearer YOUR_LONG_LIVED_ACCESS_TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 5
    icon: mdi:flash
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: "power"

# sensor.inverter_active_power
  - platform: rest
    name: "Inverter Active Power"
    unique_id: "inverter_active_power"
    resource: "http://192.168.10.24:8123/api/states/sensor.inverter_active_power"
    method: GET
    headers:
      Authorization: "Bearer YOUR_LONG_LIVED_ACCESS_TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 5
    icon: mdi:flash
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: "power"

# sensor.power_meter_active_power
  - platform: rest
    name: "Power Meter Active Power"
    unique_id: "power_meter_active_power"
    resource: "http://192.168.10.24:8123/api/states/sensor.power_meter_active_power"
    method: GET
    headers:
      Authorization: "Bearer YOUR_LONG_LIVED_ACCESS_TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 5
    icon: mdi:flash
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: "power"

# sensor.power_meter_consumption
  - platform: rest
    name: "Power Meter Consumption"
    unique_id: "power_meter_consumption"
    resource: "http://192.168.10.24:8123/api/states/sensor.power_meter_consumption"
    method: GET
    headers:
      Authorization: "Bearer YOUR_LONG_LIVED_ACCESS_TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 5
    icon: mdi:flash
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: "energy"

# sensor.battery_charge_discharge_power
  - platform: rest
    name: "Battery Charge Discharge Power"
    unique_id: "battery_charge_discharge_power"
    resource: "http://192.168.10.24:8123/api/states/sensor.battery_charge_discharge_power"
    method: GET
    headers:
      Authorization: "Bearer YOUR_LONG_LIVED_ACCESS_TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 5
    icon: mdi:home-battery-outline
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: "power"

# sensor.battery_state_of_capacity
  - platform: rest
    name: "Battery State Of Capacity"
    unique_id: "battery_state_of_capacity"
    resource: "http://192.168.10.24:8123/api/states/sensor.battery_state_of_capacity"
    method: GET
    headers:
      Authorization: "Bearer YOUR_LONG_LIVED_ACCESS_TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 30
    icon: mdi:home-battery
    unit_of_measurement: "%"
    state_class: "measurement"

# sensor.power_meter_exported
  - platform: rest
    name: "Power Meter Exported"
    unique_id: "power_meter_exported"
    resource: "http://192.168.10.24:8123/api/states/sensor.power_meter_exported"
    method: GET
    headers:
      Authorization: "Bearer YOUR_LONG_LIVED_ACCESS_TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 5
    icon: mdi:flash
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: "energy"

# sensor.battery_day_charge
  - platform: rest
    name: "Battery Day Charge"
    unique_id: "battery_day_charge"
    resource: "http://192.168.10.24:8123/api/states/sensor.battery_day_charge"
    method: GET
    headers:
      Authorization: "Bearer YOUR_LONG_LIVED_ACCESS_TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 5
    icon: mdi:battery-plus-variant
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: "energy"

# sensor.battery_day_discharge
  - platform: rest
    name: "Battery Day Discharge"
    unique_id: "battery_day_discharge"
    resource: "http://192.168.10.24:8123/api/states/sensor.battery_day_discharge"
    method: GET
    headers:
      Authorization: "Bearer YOUR_LONG_LIVED_ACCESS_TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 5
    icon: mdi:battery-minus-variant
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: "energy"

# sensor.inverter_daily_yield
  - platform: rest
    name: "Inverter Daily Yield"
    unique_id: "inverter_daily_yield"
    resource: "http://192.168.10.24:8123/api/states/sensor.inverter_daily_yield"
    method: GET
    headers:
      Authorization: "Bearer YOUR_LONG_LIVED_ACCESS_TOKEN" # Update with the access token of the source machine
      Content-Type: "application/json"
    value_template: "{{ value_json.state | float }}"
    scan_interval: 5
    icon: mdi:solar-power
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: "energy"
